'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Acteur
    Public Property Id As Integer
    Public Property Nom As String
    Public Property Prenom As String
    Public Property Adresse As String
    Public Property Cp As Nullable(Of Integer)
    Public Property Ville As String
    Public Property Pays As String
    Public Property Tel As String
    Public Property DateNaiss As Nullable(Of Date)
    Public Property NoRegistre As Nullable(Of Long)

    Public Overridable Property ConcessionnaireDe As ICollection(Of Concession) = New HashSet(Of Concession)
    Public Overridable Property PersonneContactDe As ICollection(Of Concession) = New HashSet(Of Concession)
    Public Overridable Property MentionsCommeBenef As ICollection(Of MentionBeneficiaire) = New HashSet(Of MentionBeneficiaire)

End Class
