'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CimBddContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CimBddContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Acteurs() As DbSet(Of Acteur)
    Public Overridable Property Concessions() As DbSet(Of Concession)
    Public Overridable Property Defunts() As DbSet(Of Defunt)
    Public Overridable Property Emplacements() As DbSet(Of Emplacement)
    Public Overridable Property DemNvConBenefs() As DbSet(Of FnvConBenef)
    Public Overridable Property DemandesInhumation() As DbSet(Of DemandeInhumation)
    Public Overridable Property DemandesNvConcession() As DbSet(Of DemandeNvConcession)
    Public Overridable Property MentionsBeneficiaires() As DbSet(Of MentionBeneficiaire)
    Public Overridable Property Sejours() As DbSet(Of Sejour)

End Class
