'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Concession
    Public Property Id As Integer
    Public Property Numero As Nullable(Of Integer)
    Public Property DateDebut As Nullable(Of Date)
    Public Property DateFin As Nullable(Of Date)
    Public Property MontantPaye As Nullable(Of Decimal)
    Public Property Commentaire As String
    Public Property Histoire As String
    Public Property FkEmpl As Nullable(Of Integer)
    Public Property FkCsnr As Integer
    Public Property NombreRenovations As Nullable(Of Integer)

    Public Overridable Property Concessionnaire As Acteur
    Public Overridable Property Emplacement As Emplacement
    Public Overridable Property PersonnesContact As ICollection(Of Acteur) = New HashSet(Of Acteur)
    Public Overridable Property MentionsBenefs As ICollection(Of MentionBeneficiaire) = New HashSet(Of MentionBeneficiaire)

End Class
