'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DemandeInhumation
    Public Property Id As Integer
    Public Property NumDefLh As Nullable(Of Integer)
    Public Property NumDefAnnee As Nullable(Of Integer)
    Public Property DefNom As String
    Public Property DefPrenom As String
    Public Property DefAdresse As String
    Public Property DefCp As Nullable(Of Integer)
    Public Property DefVille As String
    Public Property DefPays As String
    Public Property DefEtatCivil As String
    Public Property DefEtatCivilDe As String
    Public Property DefDateNaiss As Nullable(Of Date)
    Public Property DefLieuNaiss As String
    Public Property DefDateDeces As Nullable(Of Date)
    Public Property DefLieuDeces As String
    Public Property DmdrNom As String
    Public Property DmdrPrenom As String
    Public Property DmdrTel As String
    Public Property DmdrAdresse As String
    Public Property DmdrVille As String
    Public Property DmdrCp As Nullable(Of Integer)
    Public Property DmdrPays As String
    Public Property ConcSollic As String
    Public Property TypeEmpl As String
    Public Property RefEmpl As String
    Public Property RefAutresDef As String
    Public Property DateSign As Nullable(Of Date)
    Public Property AvisFossoy As Nullable(Of Boolean)
    Public Property Commentaire As String

    Private Property DemandesNvCon As ICollection(Of DemandeNvConcession) = New HashSet(Of DemandeNvConcession)

End Class
