'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DemandeNvConcession
    Public Property Id As Integer
    Public Property PmandNom As String
    Public Property PmandPrenom As String
    Public Property PmandDateNaiss As Nullable(Of Date)
    Public Property PmandTel As String
    Public Property PmandAdresse As String
    Public Property PmandVille As String
    Public Property PmandCp As Nullable(Of Integer)
    Public Property PmandPays As String
    Public Property CsnrNom As String
    Public Property CsnrPrenom As String
    Public Property CsnrDateNaiss As Nullable(Of Date)
    Public Property CsnrNoNational As Nullable(Of Long)
    Public Property CsnrAdresse As String
    Public Property CsnrVille As String
    Public Property CsnrCp As Nullable(Of Integer)
    Public Property CsnrPays As String
    Public Property CsnrTel As String
    Public Property TypeCon As String
    Public Property DateSign As Nullable(Of Date)
    Public Property SigneParPmand As Nullable(Of Boolean)
    Public Property Commentaire As String
    Public Property FkDemInh As Nullable(Of Integer)

    Public Overridable Property Beneficiaires As ICollection(Of FnvConBenef) = New HashSet(Of FnvConBenef)
    Public Overridable Property DemandeInhumation As DemandeInhumation

End Class
