'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emplacement
    Public Property Id As Integer
    Public Property Reference As String
    Public Property Type As String
    Public Property NbPlaces As Nullable(Of Integer)
    Public Property Commentaire As String
    Public Property MonumClasse As Nullable(Of Boolean)
    Public Property Coords As Byte()

    Public Overridable Property Concessions As ICollection(Of Concession) = New HashSet(Of Concession)
    Public Overridable Property Sejours As ICollection(Of Sejour) = New HashSet(Of Sejour)

End Class
