'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MentionBeneficiaire
    Public Property EnQualiteDe As String
    Public Property FkBenef As Integer
    Public Property FkCon As Integer

    Public Overridable Property Beneficiaire As Acteur
    Public Overridable Property Concession As Concession

End Class
