'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sejour
    Public Property Id As Integer
    Public Property DateDebut As Nullable(Of Date)
    Public Property DateFin As Nullable(Of Date)
    Public Property FkDef As Integer
    Public Property FkEmpl As Integer

    Public Overridable Property Defunt As Defunt
    Public Overridable Property Emplacement As Emplacement

End Class
